name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip openjdk-17-jdk \
          build-essential autoconf libtool pkg-config \
          zlib1g-dev libffi-dev libssl-dev

    - name: Fix Python dependencies (CRITICAL)
      run: |
        python -m pip install --upgrade pip

        # eliminar conflictos
        pip uninstall -y sh || true

        # versiones compatibles reales con p4a 2023.9.16
        pip install "sh>=1.14,<2.0"
        pip install cython==0.29.36
        pip install buildozer==1.5.0
        pip install python-for-android==2023.9.16

    - name: Clean build folders
      run: |
        rm -rf .buildozer
        rm -rf ~/.buildozer

    - name: Accept Android licenses (safe step)
      run: |
        yes | true

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-apk
        path: bin/*.apk
