name: Build Android APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build APK with Docker Kivy image
      run: |
        docker run --rm \
        -v $PWD:/home/user/hostcwd \
        kivy/buildozer:latest \
        android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
